my_config = {'config': {'mapState': {'bearing': 0,
                         'dragRotate': False,
                         'isSplit': False,
                         'latitude': 43.497262749687636,
                         'longitude': -97.69884102783509,
                         'pitch': 0,
                         'zoom': 3.6929148205987854},
            'mapStyle': {'mapStyles': {},
                         'styleType': 'dark',
                         'threeDBuildingColor': [9.665468314072013,
                                                 17.18305478057247,
                                                 31.1442867897876],
                         'topLayerGroups': {},
                         'visibleLayerGroups': {'3d building': False,
                                                'border': False,
                                                'building': True,
                                                'label': True,
                                                'land': True,
                                                'road': True,
                                                'water': True}},
            'visState': {'animationConfig': {'currentTime': None, 'speed': 1},
                         'filters': [],
                         'interactionConfig': {'brush': {'enabled': False,
                                                         'size': 0.5},
                                               'coordinate': {'enabled': False},
                                               'geocoder': {'enabled': False},
                                               'tooltip': {'compareMode': False,
                                                           'compareType': 'absolute',
                                                           'enabled': True,
                                                           'fieldsToShow': {'polygon': [{'format': None,
                                                                                         'name': 'GEOID'},
                                                                                        {'format': None,
                                                                                         'name': 'NAME'},
                                                                                        {'format': None,
                                                                                         'name': 'NAMELSAD'},
                                                                                        {'format': None,
                                                                                         'name': 'MTFCC'}],
                                                                            'tract': [{'format': None,
                                                                                       'name': 'GEOID'},
                                                                                      {'format': None,
                                                                                       'name': 'NAME'},
                                                                                      {'format': None,
                                                                                       'name': 'NAMELSAD'},
                                                                                      {'format': None,
                                                                                       'name': 'MTFCC'}]}}},
                         'layerBlending': 'normal',
                         'layers': [{'config': {'color': [72, 43, 189],
                                                'columns': {'geojson': 'geometry'},
                                                'dataId': 'tract',
                                                'hidden': False,
                                                'highlightColor': [252,
                                                                   242,
                                                                   26,
                                                                   255],
                                                'isVisible': True,
                                                'label': 'tract',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'elevationScale': 5,
                                                              'enable3d': False,
                                                              'enableElevationZoomFactor': True,
                                                              'filled': True,
                                                              'heightRange': [0,
                                                                              500],
                                                              'opacity': 0.8,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'sizeRange': [0,
                                                                            10],
                                                              'strokeColor': [179,
                                                                              173,
                                                                              158],
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'strokeOpacity': 0.8,
                                                              'stroked': True,
                                                              'thickness': 0.5,
                                                              'wireframe': False}},
                                     'id': 'zwpgn7q',
                                     'type': 'geojson',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'heightField': None,
                                                        'heightScale': 'linear',
                                                        'radiusField': None,
                                                        'radiusScale': 'linear',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}},
                                    {'config': {'color': [231, 159, 213],
                                                'columns': {'geojson': 'geometry'},
                                                'dataId': 'polygon',
                                                'hidden': False,
                                                'highlightColor': [252,
                                                                   242,
                                                                   26,
                                                                   255],
                                                'isVisible': True,
                                                'label': 'polygon',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'elevationScale': 5,
                                                              'enable3d': False,
                                                              'enableElevationZoomFactor': True,
                                                              'filled': True,
                                                              'heightRange': [0,
                                                                              500],
                                                              'opacity': 0.4,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'sizeRange': [0,
                                                                            10],
                                                              'strokeColor': [30,
                                                                              150,
                                                                              190],
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'strokeOpacity': 0.8,
                                                              'stroked': True,
                                                              'thickness': 0.5,
                                                              'wireframe': False}},
                                     'id': 'gajmc7r',
                                     'type': 'geojson',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'heightField': None,
                                                        'heightScale': 'linear',
                                                        'radiusField': None,
                                                        'radiusScale': 'linear',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}}],
                         'splitMaps': []}},
 'version': 'v1'}