my_config = {'config': {'mapState': {'bearing': 0,
                         'dragRotate': False,
                         'isSplit': False,
                         'latitude': 39.54343253191883,
                         'longitude': -94.42008582398249,
                         'pitch': 0,
                         'zoom': 10.286966133634744},
            'mapStyle': {'mapStyles': {},
                         'styleType': 'muted',
                         'threeDBuildingColor': [9.665468314072013,
                                                 17.18305478057247,
                                                 31.1442867897876],
                         'topLayerGroups': {},
                         'visibleLayerGroups': {'3d building': False,
                                                'border': False,
                                                'building': True,
                                                'label': True,
                                                'land': True,
                                                'road': True,
                                                'water': True}},
            'visState': {'animationConfig': {'currentTime': None, 'speed': 1},
                         'filters': [],
                         'interactionConfig': {'brush': {'enabled': False,
                                                         'size': 0.5},
                                               'coordinate': {'enabled': False},
                                               'geocoder': {'enabled': False},
                                               'tooltip': {'compareMode': False,
                                                           'compareType': 'absolute',
                                                           'enabled': True,
                                                           'fieldsToShow': {'full_true': [{'format': None,
                                                                                           'name': 'parcelnumb'},
                                                                                          {'format': None,
                                                                                           'name': 'address'},
                                                                                          {'format': None,
                                                                                           'name': 'owner'},
                                                                                          {'format': None,
                                                                                           'name': 'owner2'},
                                                                                          {'format': None,
                                                                                           'name': 'PropertyAddressFull'},
                                                                                          {'format': None,
                                                                                           'name': 'PartyOwner1NameFull'},
                                                                                          {'format': None,
                                                                                           'name': 'PartyOwner2NameFull'},
                                                                                          {'format': None,
                                                                                           'name': 'lat'},
                                                                                          {'format': None,
                                                                                           'name': 'PropertyLatitude'},
                                                                                          {'format': None,
                                                                                           'name': 'LegalDescription'},
                                                                                          {'format': None,
                                                                                           'name': 'legaldesc'}]}}},
                         'layerBlending': 'normal',
                         'layers': [{'config': {'color': [146, 38, 198],
                                                'columns': {'lat0': 'lat',
                                                            'lat1': 'PropertyLatitude',
                                                            'lng0': 'lon',
                                                            'lng1': 'PropertyLongitude'},
                                                'dataId': 'full_true',
                                                'hidden': False,
                                                'highlightColor': [252,
                                                                   242,
                                                                   26,
                                                                   255],
                                                'isVisible': True,
                                                'label': 'full_true_arc',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'opacity': 0.68,
                                                              'sizeRange': [0,
                                                                            10],
                                                              'targetColor': [19,
                                                                              164,
                                                                              171],
                                                              'thickness': 10.3}},
                                     'id': 'ij8adw',
                                     'type': 'arc',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear'}},
                                    {'config': {'color': [248, 149, 112],
                                                'columns': {'altitude': None,
                                                            'lat': 'lat',
                                                            'lng': 'lon'},
                                                'dataId': 'full_true',
                                                'hidden': False,
                                                'highlightColor': [252,
                                                                   242,
                                                                   26,
                                                                   255],
                                                'isVisible': True,
                                                'label': 'full_true_regrid',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'filled': True,
                                                              'fixedRadius': False,
                                                              'opacity': 0.8,
                                                              'outline': False,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'strokeColor': None,
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'thickness': 2}},
                                     'id': 'tpk8z',
                                     'type': 'point',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}},
                                    {'config': {'color': [239, 118, 158],
                                                'columns': {'altitude': None,
                                                            'lat': 'PropertyLatitude',
                                                            'lng': 'PropertyLongitude'},
                                                'dataId': 'full_true',
                                                'hidden': False,
                                                'highlightColor': [252,
                                                                   242,
                                                                   26,
                                                                   255],
                                                'isVisible': True,
                                                'label': 'full_true_attom',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'filled': True,
                                                              'fixedRadius': False,
                                                              'opacity': 0.8,
                                                              'outline': False,
                                                              'radius': 14.9,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'strokeColor': None,
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'thickness': 2}},
                                     'id': '661orzh',
                                     'type': 'point',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}}],
                         'splitMaps': []}},
 'version': 'v1'}