my_config = {'config': {'mapState': {'bearing': 0,
                         'dragRotate': False,
                         'isSplit': False,
                         'latitude': 39.027902043062845,
                         'longitude': -94.2143615537545,
                         'pitch': 0,
                         'zoom': 16.019936414786866},
            'mapStyle': {'mapStyles': {},
                         'styleType': 'dark',
                         'threeDBuildingColor': [9.665468314072013,
                                                 17.18305478057247,
                                                 31.1442867897876],
                         'topLayerGroups': {},
                         'visibleLayerGroups': {'3d building': False,
                                                'border': False,
                                                'building': True,
                                                'label': True,
                                                'land': True,
                                                'road': True,
                                                'water': True}},
            'visState': {'animationConfig': {'currentTime': None, 'speed': 1},
                         'filters': [],
                         'interactionConfig': {'brush': {'enabled': False,
                                                         'size': 0.5},
                                               'coordinate': {'enabled': False},
                                               'geocoder': {'enabled': False},
                                               'tooltip': {'compareMode': False,
                                                           'compareType': 'absolute',
                                                           'enabled': True,
                                                           'fieldsToShow': {'many1': [{'format': None,
                                                                                       'name': 'address'},
                                                                                      {'format': None,
                                                                                       'name': 'PropertyAddressFull'},
                                                                                      {'format': None,
                                                                                       'name': 'owner'},
                                                                                      {'format': None,
                                                                                       'name': 'PartyOwner1NameFull'},
                                                                                      {'format': None,
                                                                                       'name': 'aid'},
                                                                                      {'format': None,
                                                                                       'name': 'rid'},
                                                                                      {'format': None,
                                                                                       'name': 'acount'}]}}},
                         'layerBlending': 'normal',
                         'layers': [{'config': {'color': [255, 203, 153],
                                                'columns': {'altitude': None,
                                                            'lat': 'latitude',
                                                            'lng': 'longitude'},
                                                'dataId': 'many1',
                                                'hidden': False,
                                                'highlightColor': [252,
                                                                   242,
                                                                   26,
                                                                   255],
                                                'isVisible': True,
                                                'label': 'Point',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'filled': True,
                                                              'fixedRadius': False,
                                                              'opacity': 0.8,
                                                              'outline': False,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'strokeColor': None,
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'thickness': 2}},
                                     'id': '0tznzte',
                                     'type': 'point',
                                     'visualChannels': {'colorField': {'name': 'rcount',
                                                                       'type': 'integer'},
                                                        'colorScale': 'quantile',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}},
                                    {'config': {'color': [248, 149, 112],
                                                'columns': {'geojson': 'geometry'},
                                                'dataId': 'many1',
                                                'hidden': False,
                                                'highlightColor': [252,
                                                                   242,
                                                                   26,
                                                                   255],
                                                'isVisible': True,
                                                'label': 'many1',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'elevationScale': 5,
                                                              'enable3d': False,
                                                              'enableElevationZoomFactor': True,
                                                              'filled': True,
                                                              'heightRange': [0,
                                                                              500],
                                                              'opacity': 0.8,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'sizeRange': [10,
                                                                            20],
                                                              'strokeColor': [130,
                                                                              154,
                                                                              227],
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'strokeOpacity': 0.8,
                                                              'stroked': True,
                                                              'thickness': 0.5,
                                                              'wireframe': False}},
                                     'id': '8pm1dbm',
                                     'type': 'geojson',
                                     'visualChannels': {'colorField': {'name': 'acount',
                                                                       'type': 'integer'},
                                                        'colorScale': 'quantile',
                                                        'heightField': None,
                                                        'heightScale': 'linear',
                                                        'radiusField': None,
                                                        'radiusScale': 'linear',
                                                        'sizeField': {'name': 'acount',
                                                                      'type': 'integer'},
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}}],
                         'splitMaps': []}},
 'version': 'v1'}